# 通用的单数据库配置。

[alembic]
# 迁移脚本路径
script_location = alembic

# 迁移文件名生成模板，默认值为 %%(rev)s_%%(slug)s
# 如需在文件名前添加日期和时间，请取消下一行注释
# file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s

# sys.path 路径；配置后会添加到 sys.path 开头
# 默认为当前工作目录
prepend_sys_path = .

# 迁移文件内容和文件名中的日期所使用的时区
# 指定时区后需要 python-dateutil，可通过依赖项
# `alembic[tz]` 安装
# 字符串值会传给 dateutil.tz.gettz()
# 留空时使用本地时间
# timezone =

# "slug" 字段允许的最大字符数
# truncate_slug_length = 40

# 设为 'true' 时，执行 'revision' 命令会始终运行环境，
# 不受 autogenerate 是否启用的影响
# revision_environment = false

# 设为 'true' 时，versions/ 目录中没有对应 .py 源文件的
# .pyc 和 .pyo 文件也可被识别为修订版本
# sourceless = false

# 修订版本目录配置，默认为 alembic/versions
# 使用多个版本目录时，初始修订版本必须通过 --version-path 指定
# 此处路径分隔符应使用下方 version_path_separator 指定的值
# version_locations = %(here)s/bar:%(here)s/bat:alembic/versions

# 修订版本路径分隔符，用于拆分 version_locations
# 新建 alembic.ini 默认使用 "os"，即 os.pathsep
# 完全省略此配置时，会回退到按空格和/或逗号拆分的旧行为
# version_path_separator 的有效值如下：
#
# version_path_separator = :
# version_path_separator = ;
# version_path_separator = space
version_path_separator = os  # 使用 os.pathsep，新项目的默认配置

# 设为 'true' 时，在每个 version_locations 目录中递归搜索源文件
# 此配置由 Alembic 1.10 引入
# recursive_version_locations = false

# 使用 script.py.mako 写入修订文件时采用的输出编码
# output_encoding = utf-8

# sqlalchemy.url 会由 env.py 根据应用配置动态设置


[post_write_hooks]
# post_write_hooks 定义生成新修订脚本后执行的脚本或 Python 函数
# 详细说明和示例请查阅 Alembic 文档

# 使用 console_scripts 运行器调用 "black" 入口进行格式化
# post_write_hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = -l 79 REVISION_SCRIPT_FILENAME

# 使用 exec 运行器执行 "ruff"，检查并尝试修复代码
# post_write_hooks = ruff
# ruff.type = exec
# ruff.executable = %(here)s/.venv/bin/ruff
# ruff.options = --fix REVISION_SCRIPT_FILENAME

# 日志配置
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
